version: "3"
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flask_test
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "-A md5"
    restart: always
    networks:
      - app

  flask-api:
    image: strazhnyk/flask:main
    container_name: flask
    ports:
      - 5000:5000
    environment:
      DB_NAME: flask_test
      DB_USER: admin
      DB_PASS: root
      DB_HOST: db
    restart: always
    depends_on:
      - db
    networks:
      - app


  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www/:/var/www/test1
      - etc-letsencrypt:/etc/letsencrypt
      - /home/deploy/test1/:/pass/
      - www-html:/var/www/html
    depends_on:
      - flask-api
    ports:
      - 80:80
      - 443:443
    networks:
      - app

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email stragnyk@gmail.com --agree-tos --no-eff-email -d test1.cci.sh -d test2.cci.sh
    networks:
      - app

volumes:
  etc-letsencrypt:
  www-html:

networks:
 app:
   driver: bridge
