version: "3"
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flask_test
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "-A md5"
    restart: always
#    networks:
#      - app

  flask-api:
    image: strazhnyk/flask:main
    container_name: flask
    ports:
      - 5000:5000
    environment:
      DB_NAME: flask_test
      DB_USER: admin
      DB_PASS: root
      DB_HOST: db
    restart: always
    depends_on:
      - db
#    networks:
#      - app


  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
#      - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - flask-api
    ports:
      - 8081:80
#    networks:
#      - app

#  certbot:
#    image: certbot/certbot
#    depends_on:
#      - nginx
#    container_name: certbot
#    volumes:
#      - etc-letsencrypt:/etc/letsencrypt
#    command: certonly --webroot --webroot-path=/var/www/test2.cci.sh --email stragnyk@gmail.com -agree-tos --ne-eff-email -d test2.cci.sh
#    networks:
#      - app

#volumes:
#  etc-letsencrypt:

# networks:
#  app:
#    driver: bridge
