version: "3"
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flask_test
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "-A md5"
    restart: always

  flask-api:
    image: strazhnyk/flask:main
    container_name: flask
    ports:
      - 5000:5000
    environment:
      DB_NAME: flask_test
      DB_USER: admin
      DB_PASS: root
      DB_HOST: db
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.23.1
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-api
    ports:
      - 80:80
