name: Docker Flask CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Docker build and push
        run:|
          docker build ./api/ --file Dockerfile
