name: Docker Flask CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker.io
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v2
    - name: Docker build and push
      run: docker build ./api/ -t flask --file Dockerfile
      run: docker push ${{ secrets.DOCKER_LOGIN }}/flask:0.1

#   deploy:
#    needs: build_and_pub
#    runs-on: ubuntu-latest
#    steps:
#     - uses: actions/checkout@v2
#     - run: set -eu
#     - run: mkdir "$HOME/.ssh"
#     - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
#     - run: chmod 600 "$HOME/.ssh/key"
