name: Docker Flask CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1.1.0
    - name: Build the Docker image
      run: docker build ./api/Dockerfile
