name: Docker Flask CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: ./api/Dockerfile
        tags: new
