name: Docker Flask CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Docker build and push
        run:|
          docker build ./api/ -t flask --file Dockerfile
    #Setup key
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    # Deploy
    - run: rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@65.21.61.198:/root/flask
    - run: docker run flask
