name: Docker Flask CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker.io
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v2
    - name: send dockerfile
      run: scp -i ${{ secrets.KEY }} deploy@65.21.61.198:./docker-compose.yml /home/deploy
    - name: Docker build
      run: docker build ./api/ -t ${{ secrets.DOCKER_LOGIN }}/flask:${GITHUB_REF:11}
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_LOGIN }}/flask:${GITHUB_REF:11}

  deploy:
    needs: build_and_pub
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using shh
      uses: appleboy/ssh-action@master
      with:
       host: 65.21.61.198
       username: deploy
       key: ${{ secrets.KEY }}
       port: 22
       script: |
           curl https://github.com/strazhnyk/test_pig/blob/main/docker-compose.yml
           docker stop $(docker ps -a)
           docker system prune -a -f
           docker rmi $(docker images -a -q)
           docker-compose up
#           docker pull ${{ secrets.DOCKER_LOGIN }}/flask:${GITHUB_REF:11}
#           docker run --name flask -d strazhnyk/flask:main

#  deploy_compose:
#    needs: build_and_pub
#    runs-on: ubuntu-latest
#    steps:
#    - name: Deploy compose usign ssh
#      uses: wshihadeh/docker-deployment-action@v2
#      with:
#       remote_docker_host: deploy@65.21.61.198
#       ssh_private_key: ${{ secrets.PRIVATE_KEY }}
#       ssh_public_key: ${{ secrets.HOST_PUB_KEY }}
#       copy_stack_file: true
#       deploy_path: /home/deploy
#       stack_file_name: docker-compose.yml
#       args: up -d

#  deploy_compose2:
#    needs: build_and_pub
#    runs-on: ubuntu-latest
#    steps:
#    - name: add SSH
#      uses: shimataro/ssh-key-action@v2.3.1
#      with:
#        key: ${{ secrets.PRIVATE_KEY }}
#        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#        if_key_exists: replace
#    - name: deploy
#      uses: JorgenVatle/docker-compose-deploy@v1.0
#      with:
#        deploy_targets: '65.21.61.198'
#        ssh_user: 'deploy'
#        compose_file: 'docker-compose.yml'
#
